apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- ../../../fv3net/workflows/argo
kind: Kustomization
images:
- name: us.gcr.io/vcm-ml/fv3net
  newTag: 3f2e4191a6c14475307a06e227ce03421101baf1
- name: us.gcr.io/vcm-ml/post_process_run
  newTag: 3f2e4191a6c14475307a06e227ce03421101baf1
- name: us.gcr.io/vcm-ml/prognostic_run
  newTag: 3f2e4191a6c14475307a06e227ce03421101baf1