apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- ../../../fv3net/workflows/argo
kind: Kustomization
images:
- name: us.gcr.io/vcm-ml/fv3net
  newTag: ef40e9265a85b9b46eebc2b463628083758cb254
- name: us.gcr.io/vcm-ml/post_process_run
  newTag: ef40e9265a85b9b46eebc2b463628083758cb254
- name: us.gcr.io/vcm-ml/prognostic_run
  newTag: ef40e9265a85b9b46eebc2b463628083758cb254