apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- ../../../fv3net/workflows/argo
kind: Kustomization
images:
- name: us.gcr.io/vcm-ml/fv3net
  newTag: 93f31441da3d686e8579fad85f4939d14b4872b8
- name: us.gcr.io/vcm-ml/post_process_run
  newTag: 93f31441da3d686e8579fad85f4939d14b4872b8
- name: us.gcr.io/vcm-ml/prognostic_run
  newTag: 93f31441da3d686e8579fad85f4939d14b4872b8