- name: postphysics_ML_dQ1_dQ2
  config:
    random_seed: 0 
    model_type: DenseModel
    hyperparameters:
      loss: mae
      depth: 2
      fit_kwargs:
        batch_size: 512
        epochs: 24
      normalize_loss: true
      width: 128
      regularizer:
        name: l2
        kwargs:
          l: 0.0001
      optimizer:
        name: Adam
        kwargs:
          learning_rate: 0.002
    batch_function: batches_from_geodata
    batch_kwargs:
      timesteps_per_batch: 10
      mapping_function: open_nudge_to_fine
      mapping_kwargs: 
        nudging_variables:
          - "air_temperature"
          - "specific_humidity"
          - "x_wind"
          - "y_wind"
          - "pressure_thickness_of_atmospheric_layer"
    input_variables:
      - cos_zenith_angle
      - surface_geopotential
      - air_temperature
      - specific_humidity
    output_variables:
      - dQ1
      - dQ2
- name: postphysics_ML_dQu_dQv
  config:
    random_seed: 0 
    model_type: DenseModel
    hyperparameters:
      loss: mae
      depth: 2
      fit_kwargs:
        batch_size: 512
        epochs: 24
      normalize_loss: true
      width: 32
      regularizer:
        name: l2
        kwargs:
          l: 0.01
      optimizer:
        name: Adam
        kwargs:
          learning_rate: 0.002
    batch_function: batches_from_geodata
    batch_kwargs:
      timesteps_per_batch: 10
      mapping_function: open_nudge_to_fine
      mapping_kwargs: 
        nudging_variables:
          - "air_temperature"
          - "specific_humidity"
          - "x_wind"
          - "y_wind"
          - "pressure_thickness_of_atmospheric_layer"
    input_variables:
      - cos_zenith_angle
      - surface_geopotential
      - air_temperature
      - specific_humidity
      - eastward_wind
      - northward_wind
    output_variables:
      - dQu
      - dQv
