apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- ../../fv3net/workflows/argo
kind: Kustomization
images:
- name: us.gcr.io/vcm-ml/fv3net
  newTag: 50a6fa6d3702e9bef14220d1d991387196e26a7a
- name: us.gcr.io/vcm-ml/post_process_run
  newTag: 50a6fa6d3702e9bef14220d1d991387196e26a7a
- name: us.gcr.io/vcm-ml/prognostic_run
  newTag: 50a6fa6d3702e9bef14220d1d991387196e26a7a